/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import { MicrophoneIcon, MagnifyingGlassIcon } from "@heroicons/react/24/solid";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  return (
    <div className="text-3xl font-bold">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <form className="flex items-center flex-col mt-40 max-w-xl m-auto gap-6">
        <Image
          src={"/images/google-logo.png"}
          width={300}
          height={100}
          objectFit="cover"
          alt="Google Logo"
        />
        <div className="flex border border-solid border-gray-400 rounded-full items-center px-3 h-12 w-full max-w-[90%] hover:shadow-md focus-within:shadow-md">
          <MagnifyingGlassIcon className="h-5 text-gray-500" />
          <input
            type="text"
            className="focus:outline-none text-base flex-grow px-2 font-normal"
          />
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex gap-5">
          <button className="button">Google Search</button>
          <button className="button">I'm feeling lucky</button>
        </div>
      </form>
      <Footer />
    </div>
  );
};

export default Home;
