import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import MainSearch from "../components/MainSearch";

const Home: NextPage = () => {
  return (
    <div className="text-3xl font-bold">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainSearch />
      <Footer />
    </div>
  );
};

export default Home;
